# Generated by Django 3.0 on 2021-12-22 17:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion', '0003_publicacion_tema_entre1y17'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='fecha_creacion',
            field=models.DateField(verbose_name=django.utils.timezone.now),
        ),
    ]
