# Generated by Django 3.0 on 2021-12-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion', '0006_auto_20211223_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='clase',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
